var data = {
  "1": "Fortune, of all kinds, favors those who go forth boldly.",
  "2": "Rear entries must be made with caution. They can lead to great danger but great reward too.",
  "3": "A face can easily hid the desires laid behind it.",
  "4": "One who only sees through people, misses thier true importance.",
  "5": "One can only go so long without using their blade.",
  "6": "The wicked offer ideas the good may never consider.",
  "7": "A man who knows only one path is a dullard.",
  "8": "Satisfaction may be reached on the untried road.",
  "9": "'Savagery' is a term we ascribe to what we fear but do not consider.",
  "10": "Do not shame those who walk different paths peacefully.",
  "11": "Forging a new road may make a mess. But it may lead to  treasure",
  "12": "One should always remain flexible in their actions.",
  "13": "Size may give an advantage, but skill can offer one as well.",
  "14": "Be in harmony with your partners, otherwise you will suffer.",
  "15": "Communication is key to a healthy relationship.",
  "16": "Each entrance should be considered carefully.",
  "17": "A part's designed purpose may ignore possible other ones.",
  "18": "Absence makes the heart and body grow fonder.",
  "19": "One's filth may be another's trasure.",
  "20": "Sometimes the body is unwilling while the mind is not.",
  "21": "If the weapon is not to the task then it may require work.",
  "22": "A delicate touch can make anything grow.",
  "23": "Don't let your assumptions block your progress.",
  "24": "Who is hard to please may give rarely but much.",
  "25": "Who is easy to please will give often.",
  "26": "It is important to release what is inside.",
  "27": "A clean sword is one not used.",
  "28": "Grasp what you desire before you lose it.",
  "29": "Quantity may seem nice but quality is vastly more important.",
  "30": "Some pleasures are best savored slowly.",
  "31": "Life is not a race. Stop to see what is around you instead of just finishing.",
  "32": "Brute strength is not al that matters. The greatest victories lie in precision.",
  "33": "Keeping up a rapid pace will tire you out. Find a balance before you run out of energy.",
  "34": "Listening to those around you is crucial to understanding them.",
  "35": "Curiosity drives the most interesting discoveries.",
  "36": "The most sweet treats require deliberate work.",
  "37": "Do not be afraid to capture the eyes of those around you.",
  "38": "Dare to scale the highest mountains for the greatest views.",
  "39": "May you be cordial in public, and indulgent in private.",
  "40": "Sometimes the company of another can trump all other desires.",
  "41": "A pretty face may obfuscate dark intentions.",
  "42": "In all things, a desirable balance is best.",
  "43": "One may need a to practice an ignorance on the path to conquer.",
  "44": "Do not let looks blind you to possible benefits. One can always find wealth in many odd places.",
  "45": "The long or heavy sword does not a man make. Knowing how to wield is most important.",
  "46": "Boldy go into the undiscovered country.",
  "47": "There will be obstacles on your pursuits. Understand them and push on.",
  "48": "Respect the desires of others.",
  "49": "When the battle is lost, it is lost. Find your victories on other battlefields.",
  "50": "Flattery can get you quite far.",
  "51": "What you may lack in brawns can be gained in brains.",
  "52": "You are not owed anything by anyone, You must earn it.",
  "53": "Embarassing yourself will not work. A bit of wit or charm can make wonders happen.",
  "54": "Work on your strengths for they will shine to those you care to know.",
  "55": "Almost all is fair in war and love.",
  "56": "Do not besiege others. Respect their boundaries if you are unwanted.",
  "57": "Do not presume the desires of those around you.",
  "58": "A different person is a different person. Do not treat them as those you knew in the past.",
  "59": "A good night's rest comes with a sacrifice.",
  "60": "The morning sun can reveal mistakes and regrets.",
  "61": "Sometimes you will have to leap. Nothing comes from life lead in safety.",
  "62": "A laugh is worth a thousand compliments.",
  "63": "Sort out your path to victory. Seek the easiest as a foundation for harder acheivements.",
  "64": "Look to the future. The past is the past, so let it be.",
  "65": "'Too much' of a good thing is rarely a true statement.",
  "66": "Have an open mind to what is asked of you. You amy learn to enjoy it.",
  "67": "The sweetest nectar is rare to find. Love and remember every time you get it. Learn your lessons to find more.",
  "68": "Curiosity killed the cat. Satisfaction brought it back.",
  "69": "Mutual agreement may lead to mutual benefit."
}

function newStrat() {
    number = Math.floor(Math.random() * 69) + 1;
    title = "Jiruchem's Strategy #"+number;
    text = data[""+number];
    document.getElementById("title").innerHTML = title;
    document.getElementById("strategy").innerHTML = text;
}
